ALTER TABLE [DW].[DimSymbol]
    ADD CONSTRAINT [PK_DimSymbol] PRIMARY KEY CLUSTERED ([SymbolKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



