ALTER TABLE [DW].[FactTrades]
    ADD CONSTRAINT [PK_FactTrades] PRIMARY KEY CLUSTERED ([TradeKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

