#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSIS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class DataSchemaContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataSchemaContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSchemaContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSchemaContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSchemaContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<View> Views
		{
			get
			{
				return this.GetTable<View>();
			}
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
		
		public System.Data.Linq.Table<Column> Columns
		{
			get
			{
				return this.GetTable<Column>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="INFORMATION_SCHEMA.VIEWS")]
	public partial class View
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _CHECK_OPTION;
		
		private string _IS_UPDATABLE;
		
		public View()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_OPTION", DbType="VarChar(7)")]
		public string CHECK_OPTION
		{
			get
			{
				return this._CHECK_OPTION;
			}
			set
			{
				if ((this._CHECK_OPTION != value))
				{
					this._CHECK_OPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_UPDATABLE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string IS_UPDATABLE
		{
			get
			{
				return this._IS_UPDATABLE;
			}
			set
			{
				if ((this._IS_UPDATABLE != value))
				{
					this._IS_UPDATABLE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="INFORMATION_SCHEMA.TABLES")]
	public partial class Table
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _TABLE_TYPE;
		
		public Table()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_TYPE", DbType="VarChar(10)")]
		public string TABLE_TYPE
		{
			get
			{
				return this._TABLE_TYPE;
			}
			set
			{
				if ((this._TABLE_TYPE != value))
				{
					this._TABLE_TYPE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="INFORMATION_SCHEMA.COLUMNS")]
	public partial class Column
	{
		
		private string _TABLE_CATALOG;
		
		private string _TABLE_SCHEMA;
		
		private string _TABLE_NAME;
		
		private string _COLUMN_NAME;
		
		private string _IS_NULLABLE;
		
		private string _DATA_TYPE;
		
		private System.Nullable<int> _CHARACTER_MAXIMUM_LENGTH;
		
		public Column()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CATALOG", DbType="NVarChar(128)")]
		public string TABLE_CATALOG
		{
			get
			{
				return this._TABLE_CATALOG;
			}
			set
			{
				if ((this._TABLE_CATALOG != value))
				{
					this._TABLE_CATALOG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_SCHEMA", DbType="NVarChar(128)")]
		public string TABLE_SCHEMA
		{
			get
			{
				return this._TABLE_SCHEMA;
			}
			set
			{
				if ((this._TABLE_SCHEMA != value))
				{
					this._TABLE_SCHEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_NAME", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TABLE_NAME
		{
			get
			{
				return this._TABLE_NAME;
			}
			set
			{
				if ((this._TABLE_NAME != value))
				{
					this._TABLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN_NAME", DbType="NVarChar(128)")]
		public string COLUMN_NAME
		{
			get
			{
				return this._COLUMN_NAME;
			}
			set
			{
				if ((this._COLUMN_NAME != value))
				{
					this._COLUMN_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_NULLABLE", DbType="VarChar(3)")]
		public string IS_NULLABLE
		{
			get
			{
				return this._IS_NULLABLE;
			}
			set
			{
				if ((this._IS_NULLABLE != value))
				{
					this._IS_NULLABLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_TYPE", DbType="NVarChar(128)")]
		public string DATA_TYPE
		{
			get
			{
				return this._DATA_TYPE;
			}
			set
			{
				if ((this._DATA_TYPE != value))
				{
					this._DATA_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARACTER_MAXIMUM_LENGTH", DbType="Int")]
		public System.Nullable<int> CHARACTER_MAXIMUM_LENGTH
		{
			get
			{
				return this._CHARACTER_MAXIMUM_LENGTH;
			}
			set
			{
				if ((this._CHARACTER_MAXIMUM_LENGTH != value))
				{
					this._CHARACTER_MAXIMUM_LENGTH = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
