ALTER TABLE [dbo].[Desks]
    ADD CONSTRAINT [PK_Desks] PRIMARY KEY CLUSTERED ([DeskId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

