ALTER TABLE [dbo].[Trades]
    ADD CONSTRAINT [PK_Trades] PRIMARY KEY CLUSTERED ([ExecutionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

