ALTER TABLE [dbo].[TableScripts]
    ADD CONSTRAINT [PK_TableScripts] PRIMARY KEY CLUSTERED ([FileId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

