ALTER TABLE [dbo].[DeploymentLog]
    ADD CONSTRAINT [PK_DeploymentLog] PRIMARY KEY CLUSTERED ([DeploymentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

