ALTER TABLE [staging].[Symbols]
    ADD CONSTRAINT [PK_Symbols] PRIMARY KEY CLUSTERED ([SymbolId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

