#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentDBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DeploymentDb")]
	public partial class DDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DDDataContext() : 
				base(global::DeploymentDBContext.Properties.Settings.Default.DeploymentDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HasScriptBeenRun", IsComposable=true)]
		public IQueryable<HasScriptBeenRunResult> HasScriptBeenRun([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string fileName)
		{
			return this.CreateMethodCallQuery<HasScriptBeenRunResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileName);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveScriptResults")]
		public int SaveScriptResults([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string resultText)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileName, resultText);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class HasScriptBeenRunResult
	{
		
		private System.Nullable<bool> _val;
		
		public HasScriptBeenRunResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_val", DbType="Bit")]
		public System.Nullable<bool> val
		{
			get
			{
				return this._val;
			}
			set
			{
				if ((this._val != value))
				{
					this._val = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
